# Copyright 2024 The Huawei Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

if (is_ohos) {
  import("//build/config/ohos/config.gni")
  source_set("ohos") {
    visibility = [
      "//media",
      "//media/filters",
    ]

    sources = [
      "ohos_media_decoder_bridge_impl.cc",
      "ohos_media_decoder_bridge_impl.h",
    ]
    configs += [ "//media:subcomponent_config" ]

    # if (product_name == "rk3568") {
    #   defines = [ "RK3568" ]
    # }

    deps = [
      "//media/base",
      "//url",
    ]
    libs = [
      "native_media_codecbase",
      "native_media_core",
      "native_media_vdec",
      "native_window",
    ]
  }
}
